name = "KenziePack"
author = "KenzieMac130"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7075b6df11d62dcfc78738a9668d1491c95e7333e9ffc2ed99aee62bfb75dd5"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"

[options]
datapack-folder = "/config/openloader/data"
