name = "KenziePack"
author = "KenzieMac130"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "477e6b517eb04f1b6381d8bb0633dd5824f20bfd766be0e9c04b1a870f0ee078"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"

[options]
datapack-folder = "/config/openloader/data"
