name = "KenziePack"
author = "KenzieMac130"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6954b277a2dae050898316065772b528f9f4125cdf4336087c0a1c935ef58354"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"

[options]
datapack-folder = "/config/openloader/data"
