name = "KenziePack"
author = "KenzieMac130"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d2ec4f4655e6500c994fd82077325ccd7db08b91b4ff9ef26b0044b1d573bab"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"

[options]
datapack-folder = "/config/openloader/data"
