name = "KenziePack"
author = "KenzieMac130"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59324cea6f749e220b02fb8c9b7e00babff5f5684c9f5e6153eb8cc947b66041"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"
