name = "KenziePack"
author = "KenzieMac130"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0564b27495f45beaed297f0f374e49a9137711aa0abcf89939b2711e221e360c"

[versions]
fabric = "0.14.13"
minecraft = "1.19.2"

[options]
datapack-folder = "/config/openloader/data"
