// priority: 0

REIEvents.hide("item", event => {
	event.hide("campanion:rope")
	event.hide("additionaladditions:rope")
	event.hide("additionaladditions:fried_egg")
	event.hide("campanion:rope_bridge_planks")
	event.hide("campanion:rope_bridge_post")
	event.hide("bewitchment:waystone")
	event.hide("terrarianslimes:glowstick")
	event.hide("terrarianslimes:bouncy_glowstick")
	event.hide("terrarianslimes:sticky_glowstick")
	event.hide("ad_astra:hammer")
	event.hide("ad_astra:iron_plate")
	event.hide("bewitchment:cypress_broom")
	event.hide("bewitchment:dragons_blood_broom")
	event.hide("bewitchment:elder_broom")
	event.hide("bewitchment:juniper_broom")
	event.hide("bwplus:yew_broom")
	event.hide('expandeddelight:salt_rock')
	event.hide('expandeddelight:ground_salt')
	event.hide('expandeddelight:salt_ore')
	event.hide('expandeddelight:deepslate_salt_ore')
})